info:
  component: "${project.name}"

server:
  port: 8761

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  file: app.log
